### ISSUE TITLE
Use Docker-built action for publishing to Packages

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/github-actions-publish-to-github-packages#15] opened 2020-04-30 19:07 UTC
**Is your feature request related to a problem? Please describe.**
No problems / bugs at the moment.

**Describe the solution you'd like**
We should begin using the Docker-built action for publishing images to GitHub Packages. Currently, we're using [`mattdavis0351/actions/docker-gpr`](https://github.com/mattdavis0351/actions/tree/master/docker-gpr) which is ✨. However, longer term it'd make sense to use [`docker/build-push-action`](https://github.com/docker/build-push-action) so that we can rely on Docker's maintenance cadence. 

**Describe alternatives you've considered**
We can continue using the existing action with little risk.

**Additional context**
This was suggested by @decyjphr 🙇‍♂️. Courtesy pings for @ppremk and @mattdavis0351.

**Comment by mattdavis0351** [comment] 2020-04-30 19:20
Absolutely in support of this.  We should wait until workshops are complete before tinkering with this change.  There will be a pretty decent content rewrite to accommodate for how their action is used vs mine.

**Comment by ppremk** [comment] 2020-05-08 14:53
The workshop is completed. Thanks y'all for the support ❤️

**Comment by brianamarie** [comment] 2020-07-29 13:03
@mattdavis0351 @hectorsector Is this issue a duplicate of #18?

**Comment by hectorsector** [comment] 2020-07-29 13:53
> Is this issue a duplicate of #18?

I don't think so but I think @mattdavis0351 might be a better source of truth.

**Comment by mattdavis0351** [comment] 2020-07-29 17:03
@brianamarie no, this is not a duplicate.  This issue is a change in which action we use, #18 is a change in where we are storing the Docker image that the action produces.  The change will happen in relatively the same place in the course, but we shouldn't implement #18 just yet as there are still some GCR things getting ironed out

**Comment by mattdavis0351** [comment] 2020-07-30 20:12
Done!

**Closed by mattdavis0351** 2020-07-30 20:12 UTC
Labels: blocker
